### ISSUE TITLE
能不能升级eslint-plugin-vue ，支持 vue3 script setup写法

### ISSUE THREAD

**Issue by HJonping** [alibaba/f2e-spec#106]
Does not work well with <script setup>
The variables used in the <template> are warned by no-unused-vars rule
![image](https://user-images.githubusercontent.com/14228707/222091987-9531a450-ada9-46c7-a934-8250f20c3a77.png)
能不能升级eslint-plugin-vue  ，支持 vue3 script setup写法

**Comment by guoyunhe** [comment]
已升级 eslint-plugin-vue 9.x，请更新：

```
npx f2elint@latest
```
