### ISSUE TITLE
bundleDependencies 需要替换为 bundledDependencies

### ISSUE THREAD

**Issue by AielloChan** [alibaba/f2e-spec#108]
因为 bundleDependencies 已经被标记为 DEPRECATED，需要替换为 bundledDependencies。

目前 f2elint init 的时候会默认将 bundledDependencies 转换为 bundleDependencies，这是不对的

**Comment by guoyunhe** [comment]
根据 npm v10 的官方文档，`bundleDependencies` 是正确的写法：
https://docs.npmjs.com/cli/v10/configuring-npm/package-json/#bundledependencies
