### ISSUE TITLE
禁用 @typescript-eslint/indent 规则

### ISSUE THREAD

**Issue by std4453** [alibaba/f2e-spec#110]
目前 typescript 的 eslint 配置中包含 `@typescript-eslint/indent`：

https://github.com/alibaba/f2e-spec/blob/3eef290650c6fb0fdef9bbfb44c0814919ef6265/packages/eslint-config-ali/rules/typescript.js#L169

然而，该规则存在许多难以解决的问题，作者也表示目前没有资源维护，不建议使用：

https://typescript-eslint.io/rules/indent/
https://github.com/typescript-eslint/typescript-eslint/issues/1824

实践中，该规则经常会对 prettier 输出的缩进报错，比如：

```typescript
type Foo =
  | {
      a: 'b';
    }
  | {
      c: 'd';
    }
```

**Comment by guoyunhe** [comment]
新版已对 prettier 做了兼容，请升级项目配置：

```
npx f2elint@latest
```
