### ISSUE TITLE
执行f2elint scan报错

### ISSUE THREAD

**Issue by liurulin1993** [alibaba/f2e-spec#111]
TypeError: Cannot read properties of undefined (reading 'getTokens')
![image](https://user-images.githubusercontent.com/125235526/236804343-6d480ffc-42ae-4836-8a4a-f058def00ff9.png)

**Comment by cryzzchen** [comment]
@liurulin1993 后续有修复吗？我也遇到同样问题了

**Comment by xmsz-stu** [comment]
有新信息吗 我也遇到了

**Comment by guoyunhe** [comment]
请更新到最新版本：

```
tnpx f2elint@latest
```
