### ISSUE TITLE
执行f2elint fix命令时，没有忽略.eslintignore和.stylelintignore规则中的文件

### ISSUE THREAD

**Issue by yu1596882018** [alibaba/f2e-spec#117]
请问有人遇到过“执行f2elint fix命令时，没有忽略.eslintignore和.stylelintignore规则中的文件”的情况吗？有没有解决方案呢，我有2个.min.js和1个.min.css压缩文件也被格式化了，可我不想让这些压缩文件格式化

**Comment by guoyunhe** [comment]
请升级到最新版

```
npx f2elint@latest
```
