### ISSUE TITLE
只有npm的环境出现安装依赖失败

### ISSUE THREAD

**Issue by jinglu-han** [alibaba/f2e-spec#119]
我的设备环境只有npm，没有yarn/tnpm/cnpm，在安装依赖的时候报错退出
◇  ✅ 初始化项目完成
│
◇  ❌ 安装依赖失败
null

此问题是近期的提交[35e4ab9ec394bcd115a404bdd3d7f79e1d686e5b](https://github.com/alibaba/f2e-spec/commit/35e4ab9ec394bcd115a404bdd3d7f79e1d686e5b) 引入，其中对commandExists的用法存在问题：
```
else if (await commandExists('tnpm')) {
    // tnpm of Alibaba and Ant Group
    npm_command = 'tnpm';
  }

```

command-exists在命令不存在时会reject，造成如上调用抛异常退出，如下摘自[readme](https://www.npmjs.com/package/command-exists)：
```
var commandExists = require('command-exists'); 
// invoked without a callback, it returns a promise
commandExists('ls')
.then(function(command){
    // proceed
}).catch(function(){
    // command doesn't exist
});
```

问题如上，请尽快核实

**Comment by guoyunhe** [comment]
4.2.2 已修复
