### ISSUE TITLE
版本4.1.1：项目路径错误

### ISSUE THREAD

**Issue by lanseliuyiya** [alibaba/f2e-spec#122]
![1709021449479](https://github.com/alibaba/f2e-spec/assets/58325334/397a6a51-b7a3-4703-85e6-fdc07b0af383)

**Comment by TonyChanNJU** [comment]
me 2
Is there any fix for this bug？

**Comment by DOIT008** [comment]
出现了同样的问题！！

**Comment by guoyunhe** [comment]
已修复，请尝试最新版本

```bash
npx f2elint@latest
```
