### ISSUE TITLE
[f2elint]暴露 prettierr 配置项

### ISSUE THREAD

**Issue by maplor** [alibaba/f2e-spec#13]
希望有 eslint 和 stylelint 对应的配置项包，希望增加暴露 prettierr 的配置项。

**Comment by guoyunhe** [comment]
手动修改 package.json 的 prettier 字段即可修改。

**Comment by YangYongAn** [comment]
> 手动修改 package.json 的 prettier 字段即可修改。

多谢，已经看到了
