### ISSUE TITLE
npm run lint-staged出错了

### ISSUE THREAD

**Issue by siyuewuyu** [alibaba/f2e-spec#130]
Failed to load plugin 'vue' declared in '.eslintrc.js': Package subpath './lib/rules/array-bracket-spacing' is not defined by "exports" in E:\work\mojing-web\node_modules\eslint\package.json
Referenced from: E:\work\mojing-web\.eslintrc.js  这是什么报错 为什么找不到别人的记录

**Comment by guoyunhe** [comment]
请提供一下能复现问题的 git 仓库

**Comment by siyuewuyu** [comment]
我试了一下是node版本的问题 不太兼容16以及16以下的
