### ISSUE TITLE
[f2elint] 可通过函数调用使用

### ISSUE THREAD

**Issue by maplor** [alibaba/f2e-spec#14]
目前是直接对目录下的文件进行格式化操作和检查，希望增加函数调用的方式。

使用场景：
在低代码引擎转代码时，需要对生成的文件字符串进行格式化和 fix。

**Comment by lakerswgq** [comment]
https://github.com/alibaba/f2e-spec/tree/main/packages/f2elint#nodejs-api-%E4%BD%BF%E7%94%A8 

这个是支持的
