### ISSUE TITLE
为什么import { type } 会提示@typescript-eslint/no-unused-vars?

### ISSUE THREAD

**Issue by qmy777** [alibaba/f2e-spec#16]
`.eslintrc.js`
![image](https://user-images.githubusercontent.com/9345799/115861423-5afb4180-a465-11eb-80b5-452467e91d90.png)

`common.interface.ts`
![image](https://user-images.githubusercontent.com/9345799/115861602-8aaa4980-a465-11eb-880f-7f323ff49e28.png)

`Header.tsx`
![image](https://user-images.githubusercontent.com/9345799/115861738-bd544200-a465-11eb-8370-041364e6a058.png)

错误提示：
![image](https://user-images.githubusercontent.com/9345799/115861524-78301000-a465-11eb-99ac-ff966abffb32.png)

我的其他文件中 也会报相同的问题，只要我import  type 都会被提示 @typescript-eslint/no-unused-vars

**Comment by MarryJia** [comment]
我也是一样的问题，是因为eslint-config-egg 插件依赖的@typescript-eslint/parser版本低为^3.x所以yarn默认安装的3.x版本 导致4.x的支持的词法分析不生效，我通过本地安装@typescript-eslint/parser 升级为4.X，解决了这个问题

**Comment by lakerswgq** [comment]
使用 f2elint@2.0.0，`@typescript-eslint/parser` 已经升级到 5.x
