### ISSUE TITLE
f2elint commit scan与pnpm好像存在冲突

### ISSUE THREAD

**Issue by qmy777** [alibaba/f2e-spec#20]
![image](https://user-images.githubusercontent.com/9345799/118007311-9dd27a00-b37e-11eb-872e-aa58290dfa40.png)

![image](https://user-images.githubusercontent.com/9345799/118007417-b347a400-b37e-11eb-9386-4fe0f3aeee8f.png)

我不清楚你们还需要我提供什么信息？如果需要请及时告知~

**Comment by qmy777** [comment]
我目前先改成这种  可以先凑合着使用
![image](https://user-images.githubusercontent.com/9345799/118010042-39fd8080-b381-11eb-981b-79025ef359ac.png)

目测应该是pnpm的依赖项的目录结构与npm/yarn install出来的完全不一致了：
![image](https://user-images.githubusercontent.com/9345799/118010836-f9eacd80-b381-11eb-9a9a-fa6217c3d344.png)
![image](https://user-images.githubusercontent.com/9345799/118010908-0838e980-b382-11eb-9436-5d0b5119b836.png)
这么做的目的是为了做到让node_module库所依赖的内容放到一起进行共享了，可以参考这个文章：
[扁平的 node_modules 不是唯一的方法](https://pnpm.io/zh/blog/2020/05/27/flat-node-modules-is-not-the-only-way)

[pnpm](pnpm.io)

**Comment by lakerswgq** [comment]
因该和 #24 是一个问题
