### ISSUE TITLE
commitlint报错

### ISSUE THREAD

**Issue by RYTON0305** [alibaba/f2e-spec#24]
按照文档安装好f2elint后，git commit或f2elint commit-msg-scan报错“node_modules\f2elint\node_modules\.bin\commitlint”不是内部或外部命令，也不是可运行的程序或批处理文件，打开对应目录也并没有相应的文件。

**Comment by RYTON0305** [comment]
多次测试后发现可能是包管理工具使node_modules平铺导致的路径错误，用npm7安装均不能正常运行，改用yarn后有几率正常运行，不知是否是我的包管理工具配置导致的错误呢

**Comment by bianliuzhu** [comment]
我也是 这个问题有更好解决办法吗

**Comment by RYTON0305** [comment]
> 我也是 这个问题有更好解决办法吗

目前我的方法是f2elint init操作完成后，再执行yarn install，就不会报错了

**Comment by lakerswgq** [comment]
目前 commlint 的可执行文件路径是硬编码的，扁平化之后会出现问题

**Comment by lakerswgq** [comment]
fixed in `f2elint@2.0.1`
