### ISSUE TITLE
react 规约和 ts react 规约同一个文件规则不一致

### ISSUE THREAD

**Issue by sanheng** [alibaba/f2e-spec#4]
使用版本： "f2elint": "^0.4.2"

ts react 规约配置如下：

``` javascript
// .eslintrc.js
module.exports = {
  extends: 'eslint-config-ali/typescript/react',
};
```
ts react 规约会提示 lint 规则如下：

![image](https://user-images.githubusercontent.com/13793256/101616993-05407280-3a4b-11eb-9ae6-69ef07777c95.png)

但是 react 规约的不会提示，配置如下

``` javascript
// .eslintrc.js
module.exports = {
  extends: 'eslint-config-ali/react',
};
```

**Comment by lakerswgq** [comment]
@sanheng  `eslint-config-ali/typescript/react` 规则集包含了 `eslint-config-ali/react` 和 `eslint-config-ali/typescript`。`@typescript-eslint/semi` 规则在 `eslint-config-ali/typescript` 中引入，要求有分隔符，如果对风格没有特别要求，可以使用 `eslint-config-ali/essential/typescript/react`

**Comment by sanheng** [comment]
对风格没有特殊要求，只是使用了 f2elint 初始化出来就是这个。

本来使用的是 react，改了一次，现在项目中新增了 ts，那样还需要再改一次。

这样显得两个规则有点不统一。

**Comment by lakerswgq** [comment]
@sanheng 确实不太统一，`eslint` 的 `semi` 规则没法处理 class properties 的分号，需要引入 `@babel/eslint-plugin`，下个版本的迭代我们会讨论下这个问题。

这个规则是支持 autofix 的，目前切换到 ts 如果有存量的代码报这个问题可以先跑 `f2elint fix` 自动修复

**Comment by guoyunhe** [comment]
最新版应该没有这个问题了
