### ISSUE TITLE
f2elint 工具对前后端一体化应用的支持

### ISSUE THREAD

**Issue by jonjia** [alibaba/f2e-spec#41]
前后端同一个 git 仓库，目录如下，`f2e lint commit-file-scan` 在不同目录执行时会遇到问题。
1. 根目录执行会拿不到 f2elint 或 eslint 的配置
2. client、server 目录执行，会遇到 commit file 相对路径不正确的问题

目前是用 patch-package 在项目中修正了相对路径。非常期待官方能支持下这种使用场景

```
.
├── .git
├── client
│   └── .eslintrc.js
└── server
    └── .eslintrc.js
```

**Comment by lakerswgq** [comment]
第二个说的是类似 #24 的问题么

**Comment by jonjia** [comment]
> 第二个说的是类似 #24 的问题么

不是一个问题，在根目录 git commit 之后触发 hooks，拿到本次修改的文件路径是基于根目录的，直接传给 client/server 配置的 f2elint 去 lint 检查会找不到文件，结果就是检查不出问题。

**Comment by lakerswgq** [comment]
是在 client/server 目录都 init 了一次吗？

**Comment by jonjia** [comment]
> 是在 client/server 目录都 init 了一次吗？

是的，因为需要的配置不同

**Comment by guoyunhe** [comment]
这个问题在新版中应该已经修复了，使用方法：


```bash
npx f2elint # 选择 Base (JavaScript) 模板

cd client
npx f2elint # 选择 React (TypeScript) 模板

cd ../server
npx f2elint # 选择 Node (TypeScript) 模板
```
