### ISSUE TITLE
f2elint scan 没有报错但是命令行返回码是失败

### ISSUE THREAD

**Issue by guoyunhe** [alibaba/f2e-spec#48]
如下图，只有 4 个 warning 但是命令状态那里却有个❌，不知道是什么问题。

![image](https://user-images.githubusercontent.com/5836790/141752007-318ee4da-8d98-487e-912a-371f0d06eb47.png)

**Comment by qmy777** [comment]
我的更离谱
![image](https://user-images.githubusercontent.com/9345799/141752917-e5c42310-b16d-4bbe-9972-56a1fbc120c6.png)

**Comment by qmy777** [comment]
> 我的更离谱 ![image](https://user-images.githubusercontent.com/9345799/141752917-e5c42310-b16d-4bbe-9972-56a1fbc120c6.png)
> 
> 纠正下： 我执行的命令是：`f2elint commit-file-scan`

我这边发现的情况是这样的：
我其中一个临时文件，本身代码就是有问题的，f2elint也检测出来了，但是没有message记录 所以导致前面这种情况；
这种问题一旦出现，会导致暂存区的文件 永远无法被commit掉；还请官方人员尽快处理哦
![image](https://user-images.githubusercontent.com/9345799/141758300-58aefb39-ae00-454f-9a58-c9c5c920c870.png)

**Comment by lakerswgq** [comment]
@qmy777 能提供下能复现的代码文件么，仓库最好

**Comment by lakerswgq** [comment]
@qmy777 明白了，感谢，帮助很大

**Comment by lakerswgq** [comment]
f2elint@1.2.3 @qmy777
