### ISSUE TITLE
"import/named" 为什么关闭

### ISSUE THREAD

**Issue by ihaichao** [alibaba/f2e-spec#52]
"import/named" 这条规则我认为是有必要开的，可以避免 import 不存在的模块

**Comment by lakerswgq** [comment]
@bowei-jbw 你知道吗

**Comment by lakerswgq** [comment]
@ihaichao 计划下个版本打开，可以先 override

**Comment by guoyunhe** [comment]
import 插件的 bug 太多了，尤其是涉及到 webpack 等构建器配置 alias 的情况下，import 插件无法解析，容易误报，因此后续就去掉了这个插件。
