### ISSUE TITLE
希望可以加入import自动排序

### ISSUE THREAD

**Issue by JackLLLLL** [alibaba/f2e-spec#58]
"editor.codeActionsOnSave": {
  "source.sortImports": true
},

这样就可以不用关心import的顺序了~

**Comment by guoyunhe** [comment]
这个之前讨论过，但是考虑到这个排序可能不是很通用，就没有加入 f2elint。有些特殊的应用场景，import 顺序是会影响代码执行结果的，比如一些初始化脚本。

**Comment by JackLLLLL** [comment]
了解了, 感谢回复~
