### ISSUE TITLE
typescript 规约在使用 yarn 作为包管理工具时不可用

### ISSUE THREAD

**Issue by LucasIcarus** [alibaba/f2e-spec#6]
写了个简单的复现仓库  https://github.com/LucasIcarus/f2elint_test

![image](https://user-images.githubusercontent.com/15810641/103092680-01a81080-4633-11eb-8644-9ff7fb14e50c.png)

> 内网环境下使用 `tnpm` 是正常的.

但是会影响到使用 yarn workspace 功能的项目

猜测是 eslint-config-egg 依赖了旧版本的 @typescript-eslint/* 系列包导致的.

**Comment by lakerswgq** [comment]
@LucasIcarus 请尝试升级 f2elint 到最新的 1.0.3 版本再重新 init 试一下，我在复现仓库已经没出现报错了

**Comment by LucasIcarus** [comment]
@lakerswgq 

使用最新的 1.1.0 版本重新 init 后报错还在.   (重跑 init 后需要删除 node_modules 并使用 ayarn 重新安装依赖)

**Comment by lakerswgq** [comment]
@LucasIcarus 复现了
看了下发现是 `@typescript-eslint/parser` 的版本问题，`f2elint` 依赖的版本是 `4.15.2`，`f2elint` 依赖了 `eslint-config-egg`，`eslint-config-egg` 依赖了 `3.10.1` 版本的 `@typescript-eslint/parser`, `yarn` 最后用的是 `3.10.1` 版本的。
之后会修复一下这个问题。

**Comment by LucasIcarus** [comment]
@lakerswgq    大佬, 有发版本修复这个问题么?

**Comment by lakerswgq** [comment]
@LucasIcarus 暂时还没🤦‍♂️ ，yarn 的话可以仓库先配置下 `resolutions ` ，设置解析 `@typescript-eslint/parser` 的版本到 4.15.2 ，可以先解决这个问题

**Comment by melodyWxy** [comment]
包内迭代下peerDependencies字段是否能快速解决此问题？

**Comment by lakerswgq** [comment]
使用最新的 f2elint@2.0.0 ，依赖的 `eslint-config-egg` 已经升级到 10.0.0，对应的 `@typescript-eslint/parser` 版本也已经升级到了 5.x

**Comment by LucasIcarus** [comment]
牛呀.. 起项目切起来.

**Comment by LucasIcarus** [comment]
> @typescript-eslint/parser

实测还是不行. 

f2elint@2.0.0 或者 f2elint2.0.1 的 dependencies  里 eslint-config-egg 还是 ^9.0.0.   实际装下来的版本还是 9.0.0 

https://jubianchi.github.io/semver-check/#/^9.0.0/10.0.0

**Comment by LucasIcarus** [comment]
https://github.com/alibaba/f2e-spec/issues/6#issuecomment-987820896

> 使用最新的 f2elint@2.0.0 ，依赖的 `eslint-config-egg` 已经升级到 10.0.0，对应的 `@typescript-eslint/parser` 版本也已经升级到了 5.x

@lakerswgq 

2.0.0 和 2.0.1 依赖的 eslint-config-egg 还是 ^9.0.0, 对应的 semver 版本还是 9.0.0.. 是升级到 10 会有问题所以回退了么? 

https://jubianchi.github.io/semver-check/#/^9.0.0/10.0.0

**Comment by lakerswgq** [comment]
@LucasIcarus 这里漏了，`eslint-config-ali` 已经升级了，我再把 `f2elint` 升级下

**Comment by lakerswgq** [comment]
2.0.2
