### ISSUE TITLE
升级 Stylelint 到 14.x

### ISSUE THREAD

**Issue by viko16** [alibaba/f2e-spec#66]
目前内置的 stylelint 是 13.x，而 [vscode-stylelint 不再支持 stylelint 13](https://github.com/stylelint/vscode-stylelint#%EF%B8%8F-stylelint-13x-and-prior-is-no-longer-supported) 了，应当升级到 stylelint 14

**Comment by guoyunhe** [comment]
已经有 PR 了，还需要改一下
