### ISSUE TITLE
Vue项目执行 f2elint fix 时报的错误

### ISSUE THREAD

**Issue by Gzbox** [alibaba/f2e-spec#7]
![image](https://user-images.githubusercontent.com/21010051/103267538-aab48980-49ec-11eb-89c9-6a609b8826fe.png)

**Comment by lakerswgq** [comment]
@Gzbox 这个报错是没找到 `stylelint-config-ali` 这个包，这个包是包含在 f2elint 的依赖里面的，在 `f2elint init`时会安装。你执行 `f2elint init` 的时候有报错吗，如果仍有问题麻烦提供下完整复现流程

**Comment by qmy777** [comment]
> @Gzbox 这个报错是没找到 `stylelint-config-ali` 这个包，这个包是包含在 f2elint 的依赖里面的，在 `f2elint init`时会安装。你执行 `f2elint init` 的时候有报错吗，如果仍有问题麻烦提供下完整复现流程

我这边执行`f2elint`之后 倒是都会出现缺少各种依赖包的情况，比如没有`stylelint`或者`eslint`等等  ；由于我直接yarn add --dev了 所以没有上报这个问题了
我这边奇怪的时候 有时候 `f2elint`之后没有执行style相关文件的lint
