### ISSUE TITLE
f2elint scan 失败，但是f2elint commit-file-scan成功

### ISSUE THREAD

**Issue by houpengxu** [alibaba/f2e-spec#82]
我制造了个is not defined 错误，运行 f2elint scan 命令时可以发现错误。提交代码使用"pre-commit": "f2elint commit-file-scan", 时缺通过了校验。详情看图
<img width="695" alt="WX20220418-182649@2x" src="https://user-images.githubusercontent.com/20765732/163795680-f8669d60-19fa-4aab-83db-13deea545ad4.png">

**Comment by likepeach789** [comment]
遇到同样的问题。。。

**Comment by shensai06** [comment]
me too  不得不用lint-staged

**Comment by kisnows** [comment]
同样的问题

**Comment by guoyunhe** [comment]
请更新到最新版：

```
npx f2elint@latest
```
