### ISSUE TITLE
f2elint init 失败

### ISSUE THREAD

**Issue by uchief** [alibaba/f2e-spec#84]
![image](https://user-images.githubusercontent.com/94058904/168779695-79ec3b34-98fb-4a06-8d7f-9d52109d2a4d.png)

步骤如下 
![image](https://user-images.githubusercontent.com/94058904/168779893-97e44be0-7d34-4f7f-adea-d7367d30d370.png)
f2elint version: 2.2.1
node version : v16.14.2
npm version : 8.5.5
platform： mac 12.3.1

**Comment by guoyunhe** [comment]
```bash
npx f2elint@latest
# 或者
pnpm dlx f2elint@latest
# 或者
tnpx f2elint@latest
```
