### ISSUE TITLE
ignorePath is not set correctly

### ISSUE THREAD

**Issue by liuhailang** [alibaba/f2e-spec#89]
lintConfig.ignorePath = path.resolve(__dirname, '../config/_eslintignore.ejs');
must change to 
lintConfig.ignorePath = path.resolve(__dirname, '../../config/_eslintignore.ejs');

in file: getESLintConfig.ts 
    line 43

**Comment by guoyunhe** [comment]
Please update to latest version:

```
npx f2elint@latest
```
