### ISSUE TITLE
f2elint执行scan命令时，无法扫描style文件

### ISSUE THREAD

**Issue by reverocean** [alibaba/f2e-spec#90]
使用`f2elint init`命令之后，选择了styleLint，f2elint.config.js的内容如下：
```
module.exports = {
  enableStylelint: true,
  enableMarkdownlint: false,
  enablePrettier: true,
};
```
.stylelintrc.js的内容如下：
```
module.exports = {
  extends: 'stylelint-config-ali',
};
```

.stylelintignore的内容如下：
```
node_modules/
build/
dist/
coverage/
es/
lib/
**/*.min.css
**/*-min.css
**/*.bundle.css
```
这些都是自动生成的。

项目使用Less，有很多.less文件，但是只执行`f2elint scan`命令之后，查看输出没有一个跟less文件有关的输出。

后面使用`stylelint **/*.less`缺有很多less文件的错误。

经过查看源码，发现原因如下：
ESLint的参数是需要传入文件或者目录（ you can run ESLint on any file or directory ）；
StyleLint的参数是传输文件或者pattern（Files(s), glob(s)）；
但是在f2elint的源码里，给ESLint和StyleLint传入的默认参数是一样的（都是加了绝对路径的parttern），比如：
对ESLint的参数是：C:\Users\abc\**\*.{js,jsx,ts,tsx,vue}
对StyleLint的参数是：C:\Users\abc\**\*.{css,scss,less,acss}

这样的参数传给StyleLint之后，StyleLint使用Globy就无法匹配到任何Less文件，所以就无法对其进行扫描。

**Comment by guoyunhe** [comment]
最新版已修复，请更新项目配置：

```bash
npx f2elint@latest
```
