### ISSUE TITLE
建议提供其他包管理工具选项

### ISSUE THREAD

**Issue by Raaabbit** [alibaba/f2e-spec#92]
如题，目前f2elint 仅支持 tnpm和npm，能否提供命令支持使用 yarn 或 pnpm

**Comment by Jairwin-L** [comment]
+1

**Comment by guoyunhe** [comment]
目前已支持 pnpm。新版的 yarn 理论上应该也可以。f2elint 会读取 `npm_command` 这个环境变量，使用你当前运行 f2elint 的包管理器：

```
pnpm dlx f2elint@latest
```

**Comment by guoyunhe** [comment]
@Jairwin-L VS Code 插件
![图片](https://github.com/alibaba/f2e-spec/assets/5836790/ba0da73a-e4ac-468a-b3f6-6b5458bfc90e)

**Comment by Jairwin-L** [comment]
还真是“推荐插件”😂, 我还以为是有啥插件推荐的
---
你好, 顺带我再问下这个报错, 是需要安装这个[typescript-eslint](https://www.npmjs.com/package/typescript-eslint)?
<img width="725" alt="image" src="https://github.com/alibaba/f2e-spec/assets/32570960/9d81f24a-59ed-4ceb-99d7-54499bd1eb4e">

**Comment by guoyunhe** [comment]
@Jairwin-L 非公开代码库无法提供建议
