### ISSUE TITLE
HUSKY_GIT_PARAMS is removed

### ISSUE THREAD

**Issue by conorzhong** [alibaba/f2e-spec#94]
`HUSKY_GIT_PARAMS` is removed

At https://github.com/alibaba/f2e-spec/blob/main/packages/f2elint/src/cli.ts#L102

From https://github.com/typicode/husky/blob/840c4164d06d3c412caf63a9c9d7ca1af15f2165/docs/README.md#breaking-changes

**Comment by lilithyang2018** [comment]
+1  有人还在维护这个项目吗？

**Comment by guoyunhe** [comment]
请更新到最新版本：

```bash
npx f2elint@latest
# 或者
pnpm dlx f2elint@latest
# 或者
tnpx f2elint@latest
```
