### ISSUE TITLE
husky 不执行

### ISSUE THREAD

**Issue by MQL9011** [alibaba/f2e-spec#97]

**Comment by taotao7** [comment]
同问，请问解决了吗

**Comment by taotao7** [comment]
解决了，删除node_modules然后script里面加上prepare: husky install 重新装一次

**Comment by MQL9011** [comment]
解决了, 使用 husky 8+版本. 配置不在package.json中. 需要通过.husky文件里头的配置. 具体请查官方文档.
另外git仓库根目录就得是项目根目录. 不要再分文件夹, 否则也可能不执行.
